fix Task Manager error that crashes backend
throw new Error(`Task with mining ID ${miningId} doesn't exist.`);
            ^
Error: Task with mining ID rsHsgycqUx doesn't exist.