Datatable: show new & updated contacts in the top
* frontend: update packages

* SQL: Order get_contacts_table

 Order by updated_at, recency, occurrence

* Update contacts.ts

* fix Task Manager error that crashes backend

throw new Error(`Task with mining ID ${miningId} doesn't exist.`);
            ^
Error: Task with mining ID rsHsgycqUx doesn't exist.

* Update EmailEnricherFactory.ts

* show new & updated contacts in the top

- resolves #1670

* Update 20240902102000_sort_get_contacts_table.sql

fixes row duplicates

* Update contacts.ts